---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.17.1 には新しい機能強化が含まれています。 
---
= Cloud Volumes ONTAP 9.17.1 の新機能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.17.1 には新しい機能強化が含まれています。

新しい Cloud Volumes ONTAP 機能は、NetApp Console の最新バージョンでも導入されています。詳細については、Console で管理されている https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP"^]の新機能を参照してください。



== 9.17.1 P4（17 February 2026）

Cloud Volumes ONTAP 9.17.1 P4 パッチが AWS、Azure、Google Cloud でアップグレードできるようになりました。コンソールは、既存のシステムをこのパッチ リリースにアップグレードするように要求します。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.17.1P4["P4パッチで修正されたバグのリストを表示する"^]（NetApp Support Site へのログインが必要です）。



== 9.17.1 P3（2025年12月22日）

Cloud Volumes ONTAP 9.17.1 P3 パッチが AWS、Azure、Google Cloud でアップグレードできるようになりました。コンソールは、既存のシステムをこのパッチ リリースにアップグレードするように要求します。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.17.1P3["P3パッチで修正されたバグのリストを表示する"^]（NetApp Support Site へのログインが必要です）。



== 9.17.1 P2（04 December 2025）

Cloud Volumes ONTAP 9.17.1 P2 パッチが AWS、Azure、Google Cloud でアップグレードできるようになりました。NetApp Console は、既存のシステムをこのパッチ リリースにアップグレードするように要求します。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.17.1P2["P2パッチで修正されたバグのリストを表示する"^]（NetApp Support Site へのログインが必要です）。



== 9.17.1 P1（04 November 2025）

Cloud Volumes ONTAP 9.17.1 P1 パッチが AWS、Azure、Google Cloud での展開およびアップグレードに利用できるようになりました。コンソールは、既存のシステムをこのパッチ リリースにアップグレードするように要求します。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.17.1P1["P1パッチで修正されたバグのリストを表示する"^]（NetApp Support Site へのログインが必要です）。



== アップグレードに関する注意事項

このリリースへのアップグレードの詳細については、これらの注意事項をお読みください。



=== アップグレード方法

Cloud Volumes ONTAP のアップグレードは Console から完了する必要があります。System Manager または CLI を使用して Cloud Volumes ONTAP をアップグレードしないでください。これを行うと、システムの安定性に影響する可能性があります。

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["NetApp Consoleから通知があった場合にアップグレードする方法を学びます"^]。



=== サポートされているアップグレード パス

AWS、Azure、Google Cloud の 9.16.1 リリースから Cloud Volumes ONTAP 9.17.1 P1 にアップグレードできます。Console は、対象となる Cloud Volumes ONTAP システムをこのリリースにアップグレードするように促します。



=== ダウンタイム

* 単一ノード システムをアップグレードすると、システムが最大 25 分間オフラインになり、その間 I/O が中断されます。
* HA ペアのアップグレードは中断を伴わず、I/O も中断されません。この中断のないアップグレード プロセスでは、各ノードが同時にアップグレードされ、クライアントへの I/O の提供が継続されます。

